### ISSUE TITLE
Scroll In Sequence / Steps / Partial Scroll?

### ISSUE THREAD

**Issue by ssokol** [thomasrzhao/TRZNumberScrollView#3]
This control is awesome! However, there are a few additional features I would love to see it support. (I might take a crack at adding them myself, but I'm totally clueless when it comes to animation / graphics programming.)

**Sequential Scroll**
It would be useful if the view could be made to scroll in a way similar to a car's odometer. The values displayed would scroll "from" their current value "to" their new value in sequence. Something like:

```
// set the initial value (could be done in init)
odometer.setValue = 21309

// alter the value
odometer.scrollTo(value: 21310, animated: true)
```

This would create a view with its initial value to 21,309. At some point later the app would call the `scrollTo` method to get the odometer to roll forward to the next value.

**Fixed Digit Count**
It would be great if the control could be told to generate a fixed number of digits, with or without zero padding and / or thousands separation. For example, a 5 digit view with zero padding would display something like:

```
09998
09999
10000
```

A four digit view with thousands separation would look like:

```
1,125
1,126
1,127
```

**Steps**
It would be useful to be able to tell the scroll view to use a given step value for the numbers displayed (i.e. 1, 10, 100, 1000, etc.). This would cause it to display digits between the minimum and maximum values stepped using the step value. A control with 2 digits and a step value of 10 would generate a sequence of values like: 00, 10, 20, 30, 40, 50, 60, 70, 80, 90. 

**Intermediate / Fractional Values**
If the view's value property is set to some intermediate value (i.e. "45" in a control with a step of 10, or "3.5" in a sequence with a step of 1) the view would stop at the appropriate point where the intermediate value would be (i.e. value of 35 stops at the half-way point between 30 and 40).

**Display Of Preceding / Trailing Values**
There are use cases where it's important to be able to see the "trend" - either increasing or decreasing value. In this case, it would be useful to be able to request an "expanded" view where the bottom of the value above and the top of the value below are visible. This could be partial - like a slot machine - or complete (i.e. the full number above/below are visible).

**Example**
Here's a quick shot of a display that incorporates steps, intermediate value display, and the preceding/trailing values:

<img width="76" alt="scrollpic" src="https://user-images.githubusercontent.com/350268/31046319-0543a7a6-a5bc-11e7-9fd1-3bb742cf9042.png">

This example uses a step value of 20, display previous / current / next, and is currently set somewhere just short of 280.

Any idea how hard it would be to add these features? Any pointers for a motivated noob?

**Comment by thomasrzhao** [comment]
These are all great suggestions! Unfortunately, this repo isn't actively maintained anymore since I've got a full-time job now and don't have time/am not allowed to work on iOS stuff outside of work.

This control was basically designed as a more efficient drop-in replacement for JTNumberScrollAnimatedView, so it would be a pretty big effort to add in all those features. However, at least the fixed digit count feature already exists; the class takes in a String as a parameter to setText, so all you need to do is pass in a String padded with the right number of zeros. It also supports non-digits, like commas, but it won't animate those.

If you want to implement these features yourself, I would start by looking at the playScrollAnimation method, which does all the work for the actual animation. Most of the other code is just generating the images for the digits and laying them out.
